### ISSUE TITLE
Correction to index, 1

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon-scans/mbhcalc#1]
Link to 'iii, 7001' failed, as reported by @aumsanskrit.

@Andhrabharati  pointed out this is due to an error in the index for mbhcalc.

This issue documents solution to this bug.

**Comment by funderburkjim** [comment]
```
The Problem reported:
This link fails: https://sanskrit-lexicon-scans.github.io/mbhcalc/?3.7001 
```

```
Solution:
step 1:
Revise python/MBh.Calc.ed.index.Vol.s.1-4.txt
  See commit link 4158855 for the revision.

step 2:
python make_parvan_verse.py MBh.Calc.ed.index.Vol.s.1-4.txt ../parvanverse.js

add , commit, push the mbhcalc repo to Github.

Note: it takes several minutes for the https://sanskrit-lexicon-scans.github.io/mbhcalc repo to update.

Now the problem link (https://sanskrit-lexicon-scans.github.io/mbhcalc/?3.7001 ) works
```

**Comment by Andhrabharati** [comment]
Jim,

I did not guess that you would be using the **count** field as well!

The commit diff is showing that only one line is changed, for just the verse 3,7001.

I had sent you the differences for the whole of MBh. Index, having 11 changed lines.

I wish that you update the remaining 10 lines as well.

**Comment by funderburkjim** [comment]
Hi. Right -- I just noticed that It should be 6082-6099.

Am in process of correcting.

**Comment by Andhrabharati** [comment]
Here is the updated file with counts field added--
[Correction.to.MBh.Calc.ed.index.Vol.s.1-4.txt](https://github.com/user-attachments/files/17550777/Correction.to.MBh.Calc.ed.index.Vol.s.1-4.txt)

**Comment by funderburkjim** [comment]
Thanks for the Correction file!
Corrected index now processed and installed.

Now is the end of my day.
